name: Build and Test Package

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.10', '3.11', '3.12']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        cd python-mcp
        python -m pip install --upgrade pip
        pip install -e "."

    - name: Build package
      run: |
        cd python-mcp
        python -m pip install build
        python -m build

    - name: Check package
      run: |
        cd python-mcp
        python -m pip install twine
        twine check dist/*
